-- Seed spaces from lib/spaces.js static data
insert into spaces (id, slug, name, location, neighborhood, type, category, date, availability, price, cta, status, trust, expected_attendance, deadline, indoor_outdoor, food_allowed, capacity, setup_time, parking, image, gallery, description, amenities, rules, best_for, vendor_requirements, host) values
(
  'opp-1', 'walnut-creek-weekend-market', 'Walnut Creek Weekend Market',
  'Walnut Creek, CA', 'Downtown Walnut Creek', 'Vendor market', 'Makers, fashion, food',
  'Saturdays in July', 'Applications opening soon', 'From $125/vendor', 'Apply',
  'Applications opening soon', 'Verified host', '500+', 'June 18, 2026',
  'Outdoor', 'Yes, with permit', '36 vendor booths', '8:00 AM load-in',
  'Nearby garage and 15-minute loading zone', '/hero-market.png',
  '["/hero-market.png","/event-1.png","/cat-food.png"]',
  'A curated East Bay weekend market for local brands, makers, food vendors, and community sellers.',
  '["Restrooms","Security","Outdoor power access","Food truck zone","Marketing support"]',
  '["10x10 tents only","Tent weights required","No amplified sound without approval"]',
  '["Artists & makers","Clothing brands","Packaged food","Community groups"]',
  '["Seller permit if required","Product photos","Own booth setup","Food permits for prepared food"]',
  '{"name":"East Bay Pop-Ups","type":"Verified host","response":"Usually responds within 1 day","history":"Hosted 18 local markets"}'
),
(
  'opp-2', 'mission-district-boutique-takeover', 'Mission District Boutique Takeover',
  'San Francisco, CA', 'Mission District', 'Short-term retail', 'Fashion, beauty, lifestyle',
  'Weekends available', 'Request dates', 'Request pricing', 'Request',
  'Accepting requests', 'Verified venue', 'Strong street traffic', 'Rolling requests',
  'Indoor', 'Packaged goods only', 'Up to 8 vendors or one brand activation', '1 hour before opening',
  'Street loading nearby', '/images/media__1779838728727.jpg',
  '["/images/media__1779838728727.jpg","/cat-fashion.png","/cat-beauty.png"]',
  'A polished boutique environment for fashion, beauty, lifestyle, and launch moments.',
  '["Wi-Fi","Display shelves","Changing room","Restrooms","Track lighting"]',
  '["No wall damage","No loud music","Certificate of insurance may be required"]',
  '["Fashion","Beauty","Jewelry","Lifestyle products"]',
  '["Brand photos","Retail-ready display","Proof of insurance if requested"]',
  '{"name":"Maria Santos","type":"Verified venue","response":"Usually responds within 2 days","history":"Hosted 9 retail takeovers"}'
),
(
  'opp-3', 'oakland-makers-night-market', 'Oakland Makers Night Market',
  'Oakland, CA', 'Uptown Oakland', 'Evening vendor market', 'Art, vintage, jewelry',
  'Select Fridays', 'Accepting applications', 'From $95/vendor', 'Apply',
  'Accepting applications', 'Verified host', '300+', 'June 12, 2026',
  'Indoor/outdoor', 'Limited packaged food', '28 vendor booths', '4:00 PM load-in',
  'Shared lot and curbside load-in', '/images/media__1779838851661.jpg',
  '["/images/media__1779838851661.jpg","/event-2.png","/cat-vintage.png"]',
  'A Friday evening market built around makers, vintage sellers, print artists, jewelry brands, and neighborhood browsing.',
  '["Tables available","Electricity","Restrooms","Event promotion","Indoor backup area"]',
  '["Category limits apply","No open flames","Accepted vendors receive a load-in map"]',
  '["Vintage","Jewelry","Art prints","Candles"]',
  '["Product photos","Category fit","Own payment setup"]',
  '{"name":"Oakland Creative Spaces","type":"Verified host","response":"Usually responds within 1 day","history":"Hosted 12 neighborhood events"}'
),
(
  'opp-4', 'san-jose-community-market', 'San Jose Community Market',
  'San Jose, CA', 'Downtown / SoFA', 'Outdoor market', 'Food, nonprofits, local goods',
  'Venue being finalized', 'Join interest list', 'Request pricing', 'View details',
  'Venue being finalized', 'Organizer profile reviewed', '400+ projected', 'Rolling interest list',
  'Outdoor', 'Yes, with permit', '40 vendor booths', 'TBD after venue confirmation',
  'Food truck and vendor load-in planned', '/event-1.png',
  '["/event-1.png","/cat-food.png","/cat-jewelry.png"]',
  'A South Bay community market for vendors, nonprofits, food trucks, artists, and neighborhood organizations.',
  '["Food truck area","Security planned","Community partner promotion","Outdoor layout"]',
  '["Food permits required","Pack out all trash","Final booth rules shared after venue approval"]',
  '["Food vendors","Nonprofits","Artists","Local services"]',
  '["Interest form","Permit notes for food","Setup needs"]',
  '{"name":"South Bay Events Co.","type":"Reviewed organizer","response":"Usually responds within 3 days","history":"Planning community market series"}'
),
(
  'opp-5', 'berkeley-art-market-booth', 'Berkeley Art Market Booth',
  'Berkeley, CA', 'Fourth Street', 'Booth opportunity', 'Artists and handmade goods',
  'August weekends', 'Accepting applications', 'From $85/vendor', 'Apply',
  'Accepting applications', 'Verified host', '250+', 'July 10, 2026',
  'Indoor/outdoor', 'No prepared food', '20 vendor booths', '9:00 AM load-in',
  'Street parking and rear alley load-in', '/cat-jewelry.png',
  '["/cat-jewelry.png","/cat-beauty.png","/event-2.png"]',
  'A small, curated art and handmade market with room for jewelry, ceramics, prints, candles, and design-led goods.',
  '["Tables/chairs available","Limited electricity","Restrooms","Shared promotion"]',
  '["Family-friendly products only","No duplicate vendor categories beyond limits"]',
  '["Jewelry","Ceramics","Art prints","Handmade goods"]',
  '["Product images","Display description","Category approval"]',
  '{"name":"Berkeley Art Collective","type":"Verified host","response":"Usually responds within 2 days","history":"Hosted 7 artisan markets"}'
),
(
  'opp-6', 'palo-alto-lifestyle-popup', 'Palo Alto Lifestyle Pop-Up',
  'Palo Alto, CA', 'Downtown Palo Alto', 'Retail space', 'Beauty, wellness, design',
  'September dates available', 'Request dates', 'Request pricing', 'Request',
  'Accepting requests', 'Verified venue', 'High-intent retail traffic', 'Rolling requests',
  'Indoor', 'No food or beverage', 'One brand or 6 curated vendors', 'Flexible load-in by approval',
  'Paid lots nearby', '/images/media__1779840173203.jpg',
  '["/images/media__1779840173203.jpg","/cat-beauty.png","/cat-fashion.png"]',
  'A clean lifestyle pop-up space for wellness, beauty, fashion, home goods, and premium local brands.',
  '["Premium lighting","Storage area","Wi-Fi","Restrooms","Display walls"]',
  '["Curated aesthetic required","No food inside","Security deposit may apply"]',
  '["Beauty","Wellness","Lifestyle","Design-led goods"]',
  '["Brand deck or photos","Retail-ready display","Insurance if requested"]',
  '{"name":"Lumina Spaces","type":"Verified venue","response":"Usually responds within 2 days","history":"Hosted 5 lifestyle activations"}'
)
on conflict (slug) do nothing;

-- Seed events from lib/data.js static data
insert into events (event_name, slug, date, start_time, end_time, city, neighborhood, location_name, venue_status, event_type, attendee_info, access_type, description, public_description, status, vendor_applications_open, related_opportunity_slug, vendor_spots_total, vendor_spots_available, booth_price_min, booth_price_max, application_deadline, expected_attendance, expected_vendors, food_allowed, nonprofit_discount, organizer_name, parking, family_friendly, pets_allowed, food_available, accessibility, image_url, cta_text, categories) values
(
  'Bay Area Brand Market', 'bay-area-brand-market', 'Summer 2026', '11:00 AM', '5:00 PM',
  'San Ramon / East Bay', 'East Bay', 'East Bay - venue announced after confirmation',
  'Venue being finalized', 'Curated vendor market',
  'Free to attend. Final address and parking details will be shared when the venue is confirmed.',
  'Free public event',
  'A curated multi-vendor pop-up market featuring local clothing brands, accessories, vintage sellers, artists, and makers.',
  'Shop local brands, vintage sellers, artists, and makers at a Bay Area market built around small businesses and community discovery.',
  'accepting', true, 'walnut-creek-weekend-market',
  20, 15, 75, 200, 'Rolling applications', '400-600',
  'Clothing, vintage, jewelry, art, accessories', 0, 1, 'PopUpCo Market Team',
  'Parking details announced with final venue.', 'Yes', 'Venue dependent',
  'Packaged goods may be available.', 'Venue details will be confirmed before the event.',
  '/event-1.png', 'Apply to Sell', 'Clothing, Vintage, Jewelry, Art, Accessories'
),
(
  'East Bay Local Makers Pop-Up', 'east-bay-local-makers', 'Fall 2026', '10:00 AM', '4:00 PM',
  'Bay Area', 'East Bay', 'Bay Area - venue being finalized',
  'Venue being finalized', 'Maker market',
  'Free to attend. RSVP details may be added closer to the event.',
  'Free public event',
  'A neighborhood market celebrating local makers, handmade goods, art prints, vintage finds, and small-batch products.',
  'Meet local makers and shop handmade goods, art prints, vintage finds, candles, jewelry, and small-batch products.',
  'coming_soon', false, 'berkeley-art-market-booth',
  25, 25, 75, 175, 'Coming soon', '250-400',
  'Makers, vintage, art, jewelry, candles', 0, 1, 'PopUpCo Market Team',
  'Parking and load-in details coming soon.', 'Yes', 'Venue dependent',
  'Limited packaged goods.', 'Venue details will be confirmed before the event.',
  '/event-2.png', 'Join Waitlist', 'Makers, Vintage, Art, Jewelry, Candles'
),
(
  'Community Retail Weekend', 'community-retail-weekend', 'Fall 2026', '12:00 PM', '6:00 PM',
  'Bay Area', 'Bay Area', 'Bay Area - accepting venue partners',
  'Venue partner needed', 'Community market',
  'Public event details will be finalized after a venue partner is confirmed.',
  'Free or RSVP-based',
  'A community-centered pop-up weekend with space for nonprofits, local businesses, food vendors, and community organizations.',
  'A community-centered retail weekend for nonprofits, local businesses, food vendors, and neighborhood organizations.',
  'venue_needed', false, 'san-jose-community-market',
  30, 30, 75, 150, 'After venue confirmation', '400+ projected',
  'Nonprofits, food, community, local businesses', 1, 1, 'PopUpCo Community Team',
  'To be confirmed with venue partner.', 'Yes', 'Venue dependent',
  'Food vendors planned, permits required.', 'Venue details will be confirmed before the event.',
  '/event-1.png', 'Partner With Us', 'Nonprofits, Food, Community, Local Businesses'
),
(
  'Food Truck & Local Goods Market', 'food-truck-local-goods', 'TBD', 'TBD', 'TBD',
  'Bay Area', 'Bay Area', 'Bay Area - planning phase',
  'Planning phase', 'Food pop-up market',
  'Public event details will be shared when the date and venue are confirmed.',
  'Free or RSVP-based',
  'A food-forward pop-up featuring local food trucks, packaged goods, beverage vendors, and specialty food brands.',
  'A food-forward pop-up concept with local food trucks, packaged goods, beverage vendors, and specialty food brands.',
  'coming_soon', false, 'san-jose-community-market',
  15, 15, 100, 250, 'Coming soon', '300-500 projected',
  'Food trucks, packaged food, beverages', 1, 0, 'PopUpCo Food Pop-Ups',
  'Food truck and visitor parking details coming soon.', 'Yes', 'Venue dependent',
  'Yes, food vendors planned.', 'Venue details will be confirmed before the event.',
  '/event-2.png', 'Join Waitlist', 'Food Trucks, Packaged Food, Beverages'
)
on conflict (slug) do nothing;
