// Shared static marketplace data used while PopUpCo is in its beta phase.
// These records power attendee event discovery, vendor application prefill,
// upcoming event details, and sitemap generation.

export const PLACEHOLDER_EVENTS = [
  {
    id: 1,
    event_name: 'Bay Area Brand Market',
    slug: 'bay-area-brand-market',
    date: 'Summer 2026',
    startTime: '11:00 AM',
    endTime: '5:00 PM',
    city: 'San Ramon / East Bay',
    neighborhood: 'East Bay',
    location_name: 'East Bay - venue announced after confirmation',
    venueStatus: 'Venue being finalized',
    eventType: 'Curated vendor market',
    attendeeInfo: 'Free to attend. Final address and parking details will be shared when the venue is confirmed.',
    accessType: 'Free public event',
    description: 'A curated multi-vendor pop-up market featuring local clothing brands, accessories, vintage sellers, artists, and makers.',
    publicDescription: 'Shop local brands, vintage sellers, artists, and makers at a Bay Area market built around small businesses and community discovery.',
    status: 'accepting',
    vendorApplicationsOpen: true,
    relatedOpportunitySlug: 'walnut-creek-weekend-market',
    vendor_spots_total: 20,
    vendor_spots_available: 15,
    booth_price_min: 75,
    booth_price_max: 200,
    application_deadline: 'Rolling applications',
    expectedAttendance: '400-600',
    expectedVendors: 'Clothing, vintage, jewelry, art, accessories',
    food_allowed: 0,
    nonprofit_discount: 1,
    organizerName: 'PopUpCo Market Team',
    parking: 'Parking details announced with final venue.',
    familyFriendly: 'Yes',
    petsAllowed: 'Venue dependent',
    foodAvailable: 'Packaged goods may be available.',
    accessibility: 'Venue details will be confirmed before the event.',
    image_url: '/event-1.png',
    cta_text: 'Apply to Sell',
    categories: 'Clothing, Vintage, Jewelry, Art, Accessories',
  },
  {
    id: 2,
    event_name: 'East Bay Local Makers Pop-Up',
    slug: 'east-bay-local-makers',
    date: 'Fall 2026',
    startTime: '10:00 AM',
    endTime: '4:00 PM',
    city: 'Bay Area',
    neighborhood: 'East Bay',
    location_name: 'Bay Area - venue being finalized',
    venueStatus: 'Venue being finalized',
    eventType: 'Maker market',
    attendeeInfo: 'Free to attend. RSVP details may be added closer to the event.',
    accessType: 'Free public event',
    description: 'A neighborhood market celebrating local makers, handmade goods, art prints, vintage finds, and small-batch products.',
    publicDescription: 'Meet local makers and shop handmade goods, art prints, vintage finds, candles, jewelry, and small-batch products.',
    status: 'coming_soon',
    vendorApplicationsOpen: false,
    relatedOpportunitySlug: 'berkeley-art-market-booth',
    vendor_spots_total: 25,
    vendor_spots_available: 25,
    booth_price_min: 75,
    booth_price_max: 175,
    application_deadline: 'Coming soon',
    expectedAttendance: '250-400',
    expectedVendors: 'Makers, vintage, art, jewelry, candles',
    food_allowed: 0,
    nonprofit_discount: 1,
    organizerName: 'PopUpCo Market Team',
    parking: 'Parking and load-in details coming soon.',
    familyFriendly: 'Yes',
    petsAllowed: 'Venue dependent',
    foodAvailable: 'Limited packaged goods.',
    accessibility: 'Venue details will be confirmed before the event.',
    image_url: '/event-2.png',
    cta_text: 'Join Waitlist',
    categories: 'Makers, Vintage, Art, Jewelry, Candles',
  },
  {
    id: 3,
    event_name: 'Community Retail Weekend',
    slug: 'community-retail-weekend',
    date: 'Fall 2026',
    startTime: '12:00 PM',
    endTime: '6:00 PM',
    city: 'Bay Area',
    neighborhood: 'Bay Area',
    location_name: 'Bay Area - accepting venue partners',
    venueStatus: 'Venue partner needed',
    eventType: 'Community market',
    attendeeInfo: 'Public event details will be finalized after a venue partner is confirmed.',
    accessType: 'Free or RSVP-based',
    description: 'A community-centered pop-up weekend with space for nonprofits, local businesses, food vendors, and community organizations.',
    publicDescription: 'A community-centered retail weekend for nonprofits, local businesses, food vendors, and neighborhood organizations.',
    status: 'venue_needed',
    vendorApplicationsOpen: false,
    relatedOpportunitySlug: 'san-jose-community-market',
    vendor_spots_total: 30,
    vendor_spots_available: 30,
    booth_price_min: 75,
    booth_price_max: 150,
    application_deadline: 'After venue confirmation',
    expectedAttendance: '400+ projected',
    expectedVendors: 'Nonprofits, food, community, local businesses',
    food_allowed: 1,
    nonprofit_discount: 1,
    organizerName: 'PopUpCo Community Team',
    parking: 'To be confirmed with venue partner.',
    familyFriendly: 'Yes',
    petsAllowed: 'Venue dependent',
    foodAvailable: 'Food vendors planned, permits required.',
    accessibility: 'Venue details will be confirmed before the event.',
    image_url: '/event-1.png',
    cta_text: 'Partner With Us',
    categories: 'Nonprofits, Food, Community, Local Businesses',
  },
  {
    id: 4,
    event_name: 'Food Truck & Local Goods Market',
    slug: 'food-truck-local-goods',
    date: 'TBD',
    startTime: 'TBD',
    endTime: 'TBD',
    city: 'Bay Area',
    neighborhood: 'Bay Area',
    location_name: 'Bay Area - planning phase',
    venueStatus: 'Planning phase',
    eventType: 'Food pop-up market',
    attendeeInfo: 'Public event details will be shared when the date and venue are confirmed.',
    accessType: 'Free or RSVP-based',
    description: 'A food-forward pop-up featuring local food trucks, packaged goods, beverage vendors, and specialty food brands.',
    publicDescription: 'A food-forward pop-up concept with local food trucks, packaged goods, beverage vendors, and specialty food brands.',
    status: 'coming_soon',
    vendorApplicationsOpen: false,
    relatedOpportunitySlug: 'san-jose-community-market',
    vendor_spots_total: 15,
    vendor_spots_available: 15,
    booth_price_min: 100,
    booth_price_max: 250,
    application_deadline: 'Coming soon',
    expectedAttendance: '300-500 projected',
    expectedVendors: 'Food trucks, packaged food, beverages',
    food_allowed: 1,
    nonprofit_discount: 0,
    organizerName: 'PopUpCo Food Pop-Ups',
    parking: 'Food truck and visitor parking details coming soon.',
    familyFriendly: 'Yes',
    petsAllowed: 'Venue dependent',
    foodAvailable: 'Yes, food vendors planned.',
    accessibility: 'Venue details will be confirmed before the event.',
    image_url: '/event-2.png',
    cta_text: 'Join Waitlist',
    categories: 'Food Trucks, Packaged Food, Beverages',
  },
];

export const STATUS_LABELS = {
  accepting: { label: 'Vendor Applications Open', color: 'green' },
  coming_soon: { label: 'Public Details Coming Soon', color: 'orange' },
  venue_needed: { label: 'Venue Partner Needed', color: 'sage' },
  closed: { label: 'Applications Closed', color: 'neutral' },
};

export const VENDOR_CATEGORIES = [
  { label: 'Clothing & Streetwear', description: 'Fashion brands, streetwear, apparel', image: '/cat-fashion.png' },
  { label: 'Vintage & Resale', description: 'Curated vintage, thrifted, and resale', image: '/cat-vintage.png' },
  { label: 'Jewelry & Accessories', description: 'Handmade and designed accessories', image: '/cat-jewelry.png' },
  { label: 'Beauty & Wellness', description: 'Skincare, bodycare, and wellness goods', image: '/cat-beauty.png' },
  { label: 'Artists & Makers', description: 'Prints, paintings, ceramics, crafts', image: '' },
  { label: 'Sneakers & Collectibles', description: 'Deadstock, vintage, and rare finds', image: '' },
  { label: 'Food & Beverage', description: 'Artisan food, drinks, packaged goods', image: '/cat-food.png' },
  { label: 'Nonprofits & Community', description: 'Community orgs, mission-driven brands', image: '' },
];

export function getPublicEventBySlug(slug) {
  return PLACEHOLDER_EVENTS.find((event) => event.slug === slug);
}

export function getPublicEventOptions() {
  return PLACEHOLDER_EVENTS.map((event) => ({
    slug: event.slug,
    label: event.event_name,
    applicationsOpen: event.vendorApplicationsOpen,
  }));
}
