// Shared static data for events (used as fallback when DB isn't available client-side)
export const PLACEHOLDER_EVENTS = [
  {
    id: 1,
    event_name: 'Bay Area Brand Market',
    slug: 'bay-area-brand-market',
    date: 'Summer 2025',
    city: 'San Ramon / East Bay',
    location_name: 'East Bay — Venue TBD',
    description: 'A curated multi-vendor pop-up market featuring local clothing brands, accessories, vintage sellers, artists, and makers.',
    status: 'accepting',
    vendor_spots_total: 20,
    vendor_spots_available: 15,
    booth_price_min: 75,
    booth_price_max: 200,
    application_deadline: 'Rolling applications',
    food_allowed: 0,
    nonprofit_discount: 1,
    image_url: '/event-1.png',
    cta_text: 'Apply to Sell',
    categories: 'Clothing, Vintage, Jewelry, Art, Accessories',
  },
  {
    id: 2,
    event_name: 'East Bay Local Makers Pop-Up',
    slug: 'east-bay-local-makers',
    date: 'Fall 2025',
    city: 'Bay Area',
    location_name: 'Bay Area — Venue Being Finalized',
    description: 'A neighborhood market celebrating local makers, handmade goods, art prints, vintage finds, and small-batch products.',
    status: 'coming_soon',
    vendor_spots_total: 25,
    vendor_spots_available: 25,
    booth_price_min: 75,
    booth_price_max: 175,
    application_deadline: 'Coming soon',
    food_allowed: 0,
    nonprofit_discount: 1,
    image_url: '/event-2.png',
    cta_text: 'Join Waitlist',
    categories: 'Makers, Vintage, Art, Jewelry, Candles',
  },
  {
    id: 3,
    event_name: 'Community Retail Weekend',
    slug: 'community-retail-weekend',
    date: 'Fall 2025',
    city: 'Bay Area',
    location_name: 'Bay Area — Accepting Venue Partners',
    description: 'A community-centered pop-up weekend with space for nonprofits, local businesses, food vendors, and community organizations.',
    status: 'venue_needed',
    vendor_spots_total: 30,
    vendor_spots_available: 30,
    booth_price_min: 75,
    booth_price_max: 150,
    application_deadline: null,
    food_allowed: 1,
    nonprofit_discount: 1,
    image_url: '/event-1.png',
    cta_text: 'Partner With Us',
    categories: 'Nonprofits, Food, Community, Local Businesses',
  },
  {
    id: 4,
    event_name: 'Food Truck & Local Goods Market',
    slug: 'food-truck-local-goods',
    date: 'TBD',
    city: 'Bay Area',
    location_name: 'Bay Area — Planning Phase',
    description: 'A food-forward pop-up featuring local food trucks, packaged goods, beverage vendors, and specialty food brands.',
    status: 'coming_soon',
    vendor_spots_total: 15,
    vendor_spots_available: 15,
    booth_price_min: 100,
    booth_price_max: 250,
    application_deadline: null,
    food_allowed: 1,
    nonprofit_discount: 0,
    image_url: '/event-2.png',
    cta_text: 'Join Waitlist',
    categories: 'Food Trucks, Packaged Food, Beverages',
  },
];

export const STATUS_LABELS = {
  accepting: { label: 'Accepting Vendors', color: 'green' },
  coming_soon: { label: 'Coming Soon', color: 'orange' },
  venue_needed: { label: 'Venue Needed', color: 'sage' },
  closed: { label: 'Applications Closed', color: 'neutral' },
};

export const VENDOR_CATEGORIES = [
  { icon: '👗', label: 'Clothing & Streetwear', description: 'Fashion brands, streetwear, apparel' },
  { icon: '🕶️', label: 'Vintage & Resale', description: 'Curated vintage, thrifted, and resale' },
  { icon: '💍', label: 'Jewelry & Accessories', description: 'Handmade and designed accessories' },
  { icon: '🎨', label: 'Artists & Makers', description: 'Prints, paintings, ceramics, crafts' },
  { icon: '🕯️', label: 'Beauty, Candles & Skincare', description: 'Handcrafted wellness and beauty' },
  { icon: '👟', label: 'Sneakers & Collectibles', description: 'Deadstock, vintage, and rare finds' },
  { icon: '🚛', label: 'Food Trucks & Beverage', description: 'Street food, drinks, packaged goods*', note: 'Additional permits and approval may be required.' },
  { icon: '🤝', label: 'Nonprofits & Community', description: 'Community orgs, mission-driven brands' },
];
