export const SPACES_DATA = [
  {
    id: 'space-1',
    slug: 'mission-district-boutique',
    name: 'Mission District Boutique Space',
    location: 'San Francisco, CA',
    neighborhood: 'Mission District',
    type: 'Retail storefront',
    availability: 'Weekends available',
    price: 'Request pricing',
    description: 'A clean boutique-style space for apparel, accessories, and lifestyle brands. Features high ceilings, natural light, and excellent foot traffic on a vibrant street.',
    amenities: ['Electricity', 'Wi-Fi', 'Restrooms', 'Display shelves', 'Changing room'],
    rules: ['No loud music', 'Setup 1 hour before opening', 'Clean up required'],
    bestFor: ['Fashion & Streetwear', 'Jewelry & Accessories', 'Vintage & Resale'],
    host: 'Maria S.',
    image: '/space_mission.png',
  },
  {
    id: 'space-2',
    slug: 'walnut-creek-weekend-market',
    name: 'Walnut Creek Weekend Market',
    location: 'Walnut Creek, CA',
    neighborhood: 'Downtown',
    type: 'Vendor market',
    availability: 'Applications opening soon',
    price: 'From $125/vendor',
    description: 'A curated East Bay market for local brands, makers, and community vendors. Outdoor open-air market with live acoustic music and food trucks.',
    amenities: ['Outdoor area', 'Restrooms', 'Security', 'Parking nearby'],
    rules: ['Must bring own tent (10x10 max)', 'Weights required for tents'],
    bestFor: ['Artists & Makers', 'Food & Beverage', 'Community Events'],
    host: 'East Bay Pop-Ups',
    image: '/space_walnut.png',
  },
  {
    id: 'space-3',
    slug: 'downtown-oakland-retail',
    name: 'Downtown Oakland Retail Pop-Up',
    location: 'Oakland, CA',
    neighborhood: 'Downtown / Uptown',
    type: 'Short-term retail',
    availability: 'Select dates available',
    price: 'Request pricing',
    description: 'A flexible urban pop-up space for product launches, fashion, and art. Industrial aesthetic with polished concrete floors and exposed brick.',
    amenities: ['Electricity', 'Wi-Fi', 'Restrooms', 'Loading area', 'ADA accessible'],
    rules: ['No structural changes to walls', 'Security deposit required'],
    bestFor: ['Fashion & Streetwear', 'Artists & Makers', 'Beauty & Wellness'],
    host: 'Oakland Creative Spaces',
    image: '/space_oakland.png',
  },
  {
    id: 'space-4',
    slug: 'berkeley-makers-market',
    name: 'Berkeley Makers Market Booth',
    location: 'Berkeley, CA',
    neighborhood: 'Fourth Street',
    type: 'Shared market booth',
    availability: 'Coming soon',
    price: 'From $95/vendor',
    description: 'A community-friendly market opportunity for artists, makers, and small brands. Shared indoor/outdoor space fostering collaboration.',
    amenities: ['Tables/chairs available', 'Electricity (limited)', 'Restrooms'],
    rules: ['Family-friendly items only', 'Setup time strict'],
    bestFor: ['Artists & Makers', 'Jewelry & Accessories', 'Vintage & Resale'],
    host: 'Berkeley Art Collective',
    image: '/space_berkeley.png',
  },
  {
    id: 'space-5',
    slug: 'san-jose-community-market',
    name: 'San Jose Community Market',
    location: 'San Jose, CA',
    neighborhood: 'Downtown / SoFA',
    type: 'Outdoor/vendor market',
    availability: 'Venue being finalized',
    price: 'Request pricing',
    description: 'A South Bay opportunity for vendors, nonprofits, food trucks, and local businesses. Large open space perfect for diverse community gatherings.',
    amenities: ['Outdoor area', 'Food truck parking', 'Restrooms (porta-potties)', 'Security'],
    rules: ['Food vendors must have permits', 'Pack out all trash'],
    bestFor: ['Food & Beverage', 'Community Events', 'Seasonal Markets'],
    host: 'South Bay Events Co.',
    image: '/space_sanjose.png',
  },
  {
    id: 'space-6',
    slug: 'palo-alto-lifestyle-popup',
    name: 'Palo Alto Lifestyle Pop-Up',
    location: 'Palo Alto, CA',
    neighborhood: 'Downtown',
    type: 'Premium retail opportunity',
    availability: 'Coming soon',
    price: 'Request pricing',
    description: 'A polished space for lifestyle, wellness, beauty, and design-led brands. High-end finishings, track lighting, and pristine white walls.',
    amenities: ['Electricity', 'Wi-Fi', 'Restrooms', 'Premium lighting', 'Storage area'],
    rules: ['Curated aesthetic strictly enforced', 'No food or drink inside'],
    bestFor: ['Beauty & Wellness', 'Jewelry & Accessories', 'Fashion & Streetwear'],
    host: 'Lumina Spaces',
    image: '/space_paloalto.png',
  }
];
