export const SPACES_DATA = [
  {
    id: 'opp-1',
    slug: 'walnut-creek-weekend-market',
    name: 'Walnut Creek Weekend Market',
    location: 'Walnut Creek, CA',
    neighborhood: 'Downtown Walnut Creek',
    type: 'Vendor market',
    category: 'Makers, fashion, food',
    date: 'Saturdays in July',
    availability: 'Applications opening soon',
    price: 'From $125/vendor',
    cta: 'Apply',
    status: 'Applications opening soon',
    trust: 'Verified host',
    expectedAttendance: '500+',
    deadline: 'June 18, 2026',
    indoorOutdoor: 'Outdoor',
    foodAllowed: 'Yes, with permit',
    capacity: '36 vendor booths',
    setupTime: '8:00 AM load-in',
    parking: 'Nearby garage and 15-minute loading zone',
    image: '/hero-market.png',
    gallery: ['/hero-market.png', '/event-1.png', '/cat-food.png'],
    description:
      'A curated East Bay weekend market for local brands, makers, food vendors, and community sellers. Designed for approachable foot traffic, clear setup details, and a balanced vendor mix.',
    amenities: ['Restrooms', 'Security', 'Outdoor power access', 'Food truck zone', 'Marketing support'],
    rules: ['10x10 tents only', 'Tent weights required', 'No amplified sound without approval'],
    bestFor: ['Artists & makers', 'Clothing brands', 'Packaged food', 'Community groups'],
    vendorRequirements: ['Seller permit if required', 'Product photos', 'Own booth setup', 'Food permits for prepared food'],
    host: {
      name: 'East Bay Pop-Ups',
      type: 'Verified host',
      response: 'Usually responds within 1 day',
      history: 'Hosted 18 local markets',
    },
  },
  {
    id: 'opp-2',
    slug: 'mission-district-boutique-takeover',
    name: 'Mission District Boutique Takeover',
    location: 'San Francisco, CA',
    neighborhood: 'Mission District',
    type: 'Short-term retail',
    category: 'Fashion, beauty, lifestyle',
    date: 'Weekends available',
    availability: 'Request dates',
    price: 'Request pricing',
    cta: 'Request',
    status: 'Accepting requests',
    trust: 'Verified venue',
    expectedAttendance: 'Strong street traffic',
    deadline: 'Rolling requests',
    indoorOutdoor: 'Indoor',
    foodAllowed: 'Packaged goods only',
    capacity: 'Up to 8 vendors or one brand activation',
    setupTime: '1 hour before opening',
    parking: 'Street loading nearby',
    image: '/images/media__1779838728727.jpg',
    gallery: ['/images/media__1779838728727.jpg', '/cat-fashion.png', '/cat-beauty.png'],
    description:
      'A polished boutique environment for fashion, beauty, lifestyle, and launch moments. Best for brands that want a storefront feel without a long-term lease.',
    amenities: ['Wi-Fi', 'Display shelves', 'Changing room', 'Restrooms', 'Track lighting'],
    rules: ['No wall damage', 'No loud music', 'Certificate of insurance may be required'],
    bestFor: ['Fashion', 'Beauty', 'Jewelry', 'Lifestyle products'],
    vendorRequirements: ['Brand photos', 'Retail-ready display', 'Proof of insurance if requested'],
    host: {
      name: 'Maria Santos',
      type: 'Verified venue',
      response: 'Usually responds within 2 days',
      history: 'Hosted 9 retail takeovers',
    },
  },
  {
    id: 'opp-3',
    slug: 'oakland-makers-night-market',
    name: 'Oakland Makers Night Market',
    location: 'Oakland, CA',
    neighborhood: 'Uptown Oakland',
    type: 'Evening vendor market',
    category: 'Art, vintage, jewelry',
    date: 'Select Fridays',
    availability: 'Accepting applications',
    price: 'From $95/vendor',
    cta: 'Apply',
    status: 'Accepting applications',
    trust: 'Verified host',
    expectedAttendance: '300+',
    deadline: 'June 12, 2026',
    indoorOutdoor: 'Indoor/outdoor',
    foodAllowed: 'Limited packaged food',
    capacity: '28 vendor booths',
    setupTime: '4:00 PM load-in',
    parking: 'Shared lot and curbside load-in',
    image: '/images/media__1779838851661.jpg',
    gallery: ['/images/media__1779838851661.jpg', '/event-2.png', '/cat-vintage.png'],
    description:
      'A Friday evening market built around makers, vintage sellers, print artists, jewelry brands, and neighborhood browsing.',
    amenities: ['Tables available', 'Electricity', 'Restrooms', 'Event promotion', 'Indoor backup area'],
    rules: ['Category limits apply', 'No open flames', 'Accepted vendors receive a load-in map'],
    bestFor: ['Vintage', 'Jewelry', 'Art prints', 'Candles'],
    vendorRequirements: ['Product photos', 'Category fit', 'Own payment setup'],
    host: {
      name: 'Oakland Creative Spaces',
      type: 'Verified host',
      response: 'Usually responds within 1 day',
      history: 'Hosted 12 neighborhood events',
    },
  },
  {
    id: 'opp-4',
    slug: 'san-jose-community-market',
    name: 'San Jose Community Market',
    location: 'San Jose, CA',
    neighborhood: 'Downtown / SoFA',
    type: 'Outdoor market',
    category: 'Food, nonprofits, local goods',
    date: 'Venue being finalized',
    availability: 'Join interest list',
    price: 'Request pricing',
    cta: 'View details',
    status: 'Venue being finalized',
    trust: 'Organizer profile reviewed',
    expectedAttendance: '400+ projected',
    deadline: 'Rolling interest list',
    indoorOutdoor: 'Outdoor',
    foodAllowed: 'Yes, with permit',
    capacity: '40 vendor booths',
    setupTime: 'TBD after venue confirmation',
    parking: 'Food truck and vendor load-in planned',
    image: '/event-1.png',
    gallery: ['/event-1.png', '/cat-food.png', '/cat-jewelry.png'],
    description:
      'A South Bay community market for vendors, nonprofits, food trucks, artists, and neighborhood organizations. Final venue details will be shared before paid commitments.',
    amenities: ['Food truck area', 'Security planned', 'Community partner promotion', 'Outdoor layout'],
    rules: ['Food permits required', 'Pack out all trash', 'Final booth rules shared after venue approval'],
    bestFor: ['Food vendors', 'Nonprofits', 'Artists', 'Local services'],
    vendorRequirements: ['Interest form', 'Permit notes for food', 'Setup needs'],
    host: {
      name: 'South Bay Events Co.',
      type: 'Reviewed organizer',
      response: 'Usually responds within 3 days',
      history: 'Planning community market series',
    },
  },
  {
    id: 'opp-5',
    slug: 'berkeley-art-market-booth',
    name: 'Berkeley Art Market Booth',
    location: 'Berkeley, CA',
    neighborhood: 'Fourth Street',
    type: 'Booth opportunity',
    category: 'Artists and handmade goods',
    date: 'August weekends',
    availability: 'Accepting applications',
    price: 'From $85/vendor',
    cta: 'Apply',
    status: 'Accepting applications',
    trust: 'Verified host',
    expectedAttendance: '250+',
    deadline: 'July 10, 2026',
    indoorOutdoor: 'Indoor/outdoor',
    foodAllowed: 'No prepared food',
    capacity: '20 vendor booths',
    setupTime: '9:00 AM load-in',
    parking: 'Street parking and rear alley load-in',
    image: '/cat-jewelry.png',
    gallery: ['/cat-jewelry.png', '/cat-beauty.png', '/event-2.png'],
    description:
      'A small, curated art and handmade market with room for jewelry, ceramics, prints, candles, and design-led goods.',
    amenities: ['Tables/chairs available', 'Limited electricity', 'Restrooms', 'Shared promotion'],
    rules: ['Family-friendly products only', 'No duplicate vendor categories beyond limits'],
    bestFor: ['Jewelry', 'Ceramics', 'Art prints', 'Handmade goods'],
    vendorRequirements: ['Product images', 'Display description', 'Category approval'],
    host: {
      name: 'Berkeley Art Collective',
      type: 'Verified host',
      response: 'Usually responds within 2 days',
      history: 'Hosted 7 artisan markets',
    },
  },
  {
    id: 'opp-6',
    slug: 'palo-alto-lifestyle-popup',
    name: 'Palo Alto Lifestyle Pop-Up',
    location: 'Palo Alto, CA',
    neighborhood: 'Downtown Palo Alto',
    type: 'Retail space',
    category: 'Beauty, wellness, design',
    date: 'September dates available',
    availability: 'Request dates',
    price: 'Request pricing',
    cta: 'Request',
    status: 'Accepting requests',
    trust: 'Verified venue',
    expectedAttendance: 'High-intent retail traffic',
    deadline: 'Rolling requests',
    indoorOutdoor: 'Indoor',
    foodAllowed: 'No food or beverage',
    capacity: 'One brand or 6 curated vendors',
    setupTime: 'Flexible load-in by approval',
    parking: 'Paid lots nearby',
    image: '/images/media__1779840173203.jpg',
    gallery: ['/images/media__1779840173203.jpg', '/cat-beauty.png', '/cat-fashion.png'],
    description:
      'A clean lifestyle pop-up space for wellness, beauty, fashion, home goods, and premium local brands.',
    amenities: ['Premium lighting', 'Storage area', 'Wi-Fi', 'Restrooms', 'Display walls'],
    rules: ['Curated aesthetic required', 'No food inside', 'Security deposit may apply'],
    bestFor: ['Beauty', 'Wellness', 'Lifestyle', 'Design-led goods'],
    vendorRequirements: ['Brand deck or photos', 'Retail-ready display', 'Insurance if requested'],
    host: {
      name: 'Lumina Spaces',
      type: 'Verified venue',
      response: 'Usually responds within 2 days',
      history: 'Hosted 5 lifestyle activations',
    },
  },
];

export const OPPORTUNITY_TABS = [
  'All',
  'Vendor Markets',
  'Booth Opportunities',
  'Retail Spaces',
  'Food Pop-Ups',
  'Community Events',
  'Event Venues',
  'Upcoming Pop-Ups',
];

export function getOpportunityBySlug(slug) {
  return SPACES_DATA.find((space) => space.slug === slug);
}
